[package]
name = "git-rebase-all"
version = "0.0.0"
authors = ["Tobias Bieniek <tobias@bieniek.cloud>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
